version: "3.8"

services:
  # Laravel (PHP + Artisan + Composer)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  # PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Adminer
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  # Frontend Vue 3
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "8082:8082"
    volumes:
      - ./frontend:/app
    command: npm run dev

volumes:
  postgres_data:
